version: '3'

services:
  mongoservice:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 3333:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: geuser
      ME_CONFIG_BASICAUTH_PASSWORD: geuser
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - mongoservice
    depends_on:
      - mongoservice